# Generated by Django 3.0.5 on 2024-04-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20240414_1420'),
        ('user_panel', '0002_auto_20240415_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_booking2',
            new_name='Session_book',
        ),
        migrations.AlterModelTable(
            name='session_book',
            table='Session_book',
        ),
    ]
