# Generated by Django 3.0.5 on 2024-04-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20240414_1420'),
        ('user_panel', '0004_auto_20240415_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='Session_booking',
        ),
        migrations.AlterModelTable(
            name='session_booking',
            table='Session_booking',
        ),
    ]
